### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by mysticaltech** [dlenski/motoflash2sh#2]
Hello, no issues, I just wanted to say thanks! I was struggling with the fastboot commands, trying to find ressources, and wasn't sure how to interpret the flashfile.xml... Your tool made it a childs play! My phone just booted again 😅🎉, thanks again for sharing!

**Comment by dlenski** [comment]
Very glad to hear it! You're the first actual user I know of :sunglasses:

**Comment by mysticaltech** [comment]
Ah fantastic, happy to be that one! 🙂 Cheers and be safe in these crazy times.
