### ISSUE TITLE
motoflash2sh doesn't work on Ubuntu 22.04?

### ISSUE THREAD

**Issue by NOTEVNISABELLA** [dlenski/motoflash2sh#4]
I'm trying to go back to stock firmware, but when I tried using this, it kept throwing this error [attachment]
![image](https://github.com/dlenski/motoflash2sh/assets/148576812/fa04c2b7-1c7f-42e6-9e62-89c6cae98e98)
I tried adding /.local/bin to PATH again and it did work, but it said that motoflash2sh didnt find a module named that. Any help is appreciated!

**Comment by dlenski** [comment]
This doesn't appear to have anything to do with `motoflash2sh` per se. How did you *install* it?

**Comment by lucasmz-dev** [comment]
btw i had this issue but instead of installing the tag installing from the last commit solved the issue

**Comment by dlenski** [comment]
I've (slightly) updated and modernized the `setup.py` in 30ac18a and tagged it as [v0.4](https://github.com/dlenski/motoflash2sh/releases/tag/v0.4).

**Comment by lucasmz-dev** [comment]
Correction: it might have actually been the fact I copied the command from the readme page, and on there, it's on 0.1.
